version: "3"
services:
  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - 27000:27017
#    command: --smallfiles
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "myapi"
    ports:
      - 9091:8080
    links:
      - mongo