server:
  port: 3008
logging:
  org:
    springframework:
      web:
        filter:
          CommonsRequestLoggingFilter: DEBUG
spring:
  profiles: dev
  data:
    mongodb:
      database: twitter
      username: twitter
      password: twitterPassword
  aws:
    sqsUrl: ${AWS_SQS_URL}
    accessKey: ${AWS_ACCESS_KEY}
    accessKeySecret: ${AWS_ACCESS_KEY_SECRET}
    region: ${AWS_REGION}
---
server:
    port: 3008
spring:
  profiles: kube
  data:
    mongodb:
      uri: ${MONGO_URL}
  aws:
    sqsUrl: ${AWS_SQS_URL}
    accessKey: ${AWS_ACCESS_KEY}
    accessKeySecret: ${AWS_ACCESS_KEY_SECRET}
    region: ${AWS_REGION}
logging:
  org:
    springframework:
      web:
        filter:
          CommonsRequestLoggingFilter: DEBUG